name: Deploy Jupyter Book to GitHub Pages

on:
    push:
        tags:
            - '*'

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.10'

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install jupyter-book ghp-import

            - name: Build Jupyter Book
              run: jupyter-book build .

            - name: Deploy to GitHub Pages
              if: success()
              run: |
                    ghp-import -n -p -f _build/html