name: Jupyter Book and GitHub Pages

on:
    push:
      branches: ["**"] # build on any branch
      tags: ["*"] # deploy on any tag
    pull_request: # build on any pull request

permissions:
  contents: write

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.10'

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install jupyter-book ghp-import

            - name: Build Jupyter Book
              run: jupyter-book build danra-book/

            - name: Deploy to GitHub Pages
              if: startsWith(github.ref, 'refs/tags/')
              run: |
                    ghp-import -n -p -f danra-book/_build/html